
ci_template: &CI_TEMPLATE
  only_if: >
    $CIRRUS_BRANCH =~ 'pull/.*' ||
    $CIRRUS_BRANCH == 'master' ||
    $CIRRUS_BRANCH =~ 'release/.*'

  test_script: ./ci/test.sh

linux_task:
  container:
    dockerfile: ci/ubuntu-18.04/Dockerfile
  << : *CI_TEMPLATE

# osx_task:
#   osx_instance:
#     image: mojave-base
#   << : *CI_TEMPLATE
