
ci_template: &CI_TEMPLATE
  only_if: $CIRRUS_BRANCH == 'master' || $CIRRUS_PR != ''
  test_script: ./ci/test1.sh

linux_task:
  container:
    matrix:
      - dockerfile: ci/ubuntu-18.04/Dockerfile
  << : *CI_TEMPLATE

