name: CI Notifications
on: [check_suite]
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send CI Notification Email
        uses: docker://cirrusactions/email:latest
        env:
          APP_NAME: "Cirrus CI"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MAIL_FROM: ${{ secrets.MAIL_FROM }}
          MAIL_HOST: ${{ secrets.MAIL_HOST }}
          MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
          MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
